const teamJSON = [
  {
    code: 3,
    draw: 0,
    form: null,
    id: 1,
    loss: 0,
    name: "Arsenal",
    played: 0,
    points: 0,
    position: 0,
    short_name: "ARS",
    strength: 4,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1200,
    strength_overall_away: 1270,
    strength_attack_home: 1150,
    strength_attack_away: 1210,
    strength_defence_home: 1190,
    strength_defence_away: 1220,
    pulse_id: 1
    },
    {
    code: 7,
    draw: 0,
    form: null,
    id: 2,
    loss: 0,
    name: "Aston Villa",
    played: 0,
    points: 0,
    position: 0,
    short_name: "AVL",
    strength: 3,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1090,
    strength_overall_away: 1100,
    strength_attack_home: 1140,
    strength_attack_away: 1110,
    strength_defence_home: 1090,
    strength_defence_away: 1090,
    pulse_id: 2
    },
    {
    code: 91,
    draw: 0,
    form: null,
    id: 3,
    loss: 0,
    name: "Bournemouth",
    played: 0,
    points: 0,
    position: 0,
    short_name: "BOU",
    strength: 2,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1050,
    strength_overall_away: 1050,
    strength_attack_home: 1080,
    strength_attack_away: 1130,
    strength_defence_home: 1060,
    strength_defence_away: 1100,
    pulse_id: 127
    },
    {
    code: 94,
    draw: 0,
    form: null,
    id: 4,
    loss: 0,
    name: "Brentford",
    played: 0,
    points: 0,
    position: 0,
    short_name: "BRE",
    strength: 3,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1090,
    strength_overall_away: 1100,
    strength_attack_home: 1120,
    strength_attack_away: 1150,
    strength_defence_home: 1080,
    strength_defence_away: 1120,
    pulse_id: 130
    },
    {
    code: 36,
    draw: 0,
    form: null,
    id: 5,
    loss: 0,
    name: "Brighton",
    played: 0,
    points: 0,
    position: 0,
    short_name: "BHA",
    strength: 3,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1100,
    strength_overall_away: 1090,
    strength_attack_home: 1160,
    strength_attack_away: 1160,
    strength_defence_home: 1100,
    strength_defence_away: 1120,
    pulse_id: 131
    },
    {
    code: 8,
    draw: 0,
    form: null,
    id: 6,
    loss: 0,
    name: "Chelsea",
    played: 0,
    points: 0,
    position: 0,
    short_name: "CHE",
    strength: 4,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1270,
    strength_overall_away: 1280,
    strength_attack_home: 1300,
    strength_attack_away: 1300,
    strength_defence_home: 1250,
    strength_defence_away: 1290,
    pulse_id: 4
    },
    {
    code: 31,
    draw: 0,
    form: null,
    id: 7,
    loss: 0,
    name: "Crystal Palace",
    played: 0,
    points: 0,
    position: 0,
    short_name: "CRY",
    strength: 3,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1090,
    strength_overall_away: 1100,
    strength_attack_home: 1110,
    strength_attack_away: 1160,
    strength_defence_home: 1080,
    strength_defence_away: 1160,
    pulse_id: 6
    },
    {
    code: 11,
    draw: 0,
    form: null,
    id: 8,
    loss: 0,
    name: "Everton",
    played: 0,
    points: 0,
    position: 0,
    short_name: "EVE",
    strength: 3,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1050,
    strength_overall_away: 1100,
    strength_attack_home: 1130,
    strength_attack_away: 1090,
    strength_defence_home: 1110,
    strength_defence_away: 1110,
    pulse_id: 7
    },
    {
    code: 54,
    draw: 0,
    form: null,
    id: 9,
    loss: 0,
    name: "Fulham",
    played: 0,
    points: 0,
    position: 0,
    short_name: "FUL",
    strength: 2,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1040,
    strength_overall_away: 1060,
    strength_attack_home: 1090,
    strength_attack_away: 1040,
    strength_defence_home: 1120,
    strength_defence_away: 1070,
    pulse_id: 34
    },
    {
    code: 13,
    draw: 0,
    form: null,
    id: 10,
    loss: 0,
    name: "Leicester",
    played: 0,
    points: 0,
    position: 0,
    short_name: "LEI",
    strength: 3,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1110,
    strength_overall_away: 1240,
    strength_attack_home: 1100,
    strength_attack_away: 1080,
    strength_defence_home: 1150,
    strength_defence_away: 1160,
    pulse_id: 26
    },
    {
    code: 2,
    draw: 0,
    form: null,
    id: 11,
    loss: 0,
    name: "Leeds",
    played: 0,
    points: 0,
    position: 0,
    short_name: "LEE",
    strength: 2,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1070,
    strength_overall_away: 1070,
    strength_attack_home: 1080,
    strength_attack_away: 1070,
    strength_defence_home: 1100,
    strength_defence_away: 1100,
    pulse_id: 9
    },
    {
    code: 14,
    draw: 0,
    form: null,
    id: 12,
    loss: 0,
    name: "Liverpool",
    played: 0,
    points: 0,
    position: 0,
    short_name: "LIV",
    strength: 5,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1350,
    strength_overall_away: 1360,
    strength_attack_home: 1300,
    strength_attack_away: 1350,
    strength_defence_home: 1340,
    strength_defence_away: 1350,
    pulse_id: 10
    },
    {
    code: 43,
    draw: 0,
    form: null,
    id: 13,
    loss: 0,
    name: "Man City",
    played: 0,
    points: 0,
    position: 0,
    short_name: "MCI",
    strength: 5,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1350,
    strength_overall_away: 1370,
    strength_attack_home: 1340,
    strength_attack_away: 1360,
    strength_defence_home: 1340,
    strength_defence_away: 1360,
    pulse_id: 11
    },
    {
    code: 1,
    draw: 0,
    form: null,
    id: 14,
    loss: 0,
    name: "Man Utd",
    played: 0,
    points: 0,
    position: 0,
    short_name: "MUN",
    strength: 4,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1170,
    strength_overall_away: 1250,
    strength_attack_home: 1170,
    strength_attack_away: 1190,
    strength_defence_home: 1190,
    strength_defence_away: 1200,
    pulse_id: 12
    },
    {
    code: 4,
    draw: 0,
    form: null,
    id: 15,
    loss: 0,
    name: "Newcastle",
    played: 0,
    points: 0,
    position: 0,
    short_name: "NEW",
    strength: 3,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1110,
    strength_overall_away: 1190,
    strength_attack_home: 1050,
    strength_attack_away: 1030,
    strength_defence_home: 1040,
    strength_defence_away: 1070,
    pulse_id: 23
    },
    {
    code: 17,
    draw: 0,
    form: null,
    id: 16,
    loss: 0,
    name: "Nott'm Forest",
    played: 0,
    points: 0,
    position: 0,
    short_name: "NFO",
    strength: 2,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1040,
    strength_overall_away: 1060,
    strength_attack_home: 1040,
    strength_attack_away: 1040,
    strength_defence_home: 1040,
    strength_defence_away: 1030,
    pulse_id: 15
    },
    {
    code: 20,
    draw: 0,
    form: null,
    id: 17,
    loss: 0,
    name: "Southampton",
    played: 0,
    points: 0,
    position: 0,
    short_name: "SOU",
    strength: 3,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1060,
    strength_overall_away: 1090,
    strength_attack_home: 1090,
    strength_attack_away: 1140,
    strength_defence_home: 1120,
    strength_defence_away: 1090,
    pulse_id: 20
    },
    {
    code: 6,
    draw: 0,
    form: null,
    id: 18,
    loss: 0,
    name: "Spurs",
    played: 0,
    points: 0,
    position: 0,
    short_name: "TOT",
    strength: 4,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1210,
    strength_overall_away: 1270,
    strength_attack_home: 1190,
    strength_attack_away: 1200,
    strength_defence_home: 1210,
    strength_defence_away: 1210,
    pulse_id: 21
    },
    {
    code: 21,
    draw: 0,
    form: null,
    id: 19,
    loss: 0,
    name: "West Ham",
    played: 0,
    points: 0,
    position: 0,
    short_name: "WHU",
    strength: 3,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1110,
    strength_overall_away: 1170,
    strength_attack_home: 1110,
    strength_attack_away: 1150,
    strength_defence_home: 1160,
    strength_defence_away: 1180,
    pulse_id: 25
    },
    {
    code: 39,
    draw: 0,
    form: null,
    id: 20,
    loss: 0,
    name: "Wolves",
    played: 0,
    points: 0,
    position: 0,
    short_name: "WOL",
    strength: 3,
    team_division: null,
    unavailable: false,
    win: 0,
    strength_overall_home: 1100,
    strength_overall_away: 1100,
    strength_attack_home: 1150,
    strength_attack_away: 1160,
    strength_defence_home: 1080,
    strength_defence_away: 1100,
    pulse_id: 38
  }
]



export default teamJSON;